name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses:  actions/setup-java@v1
        with:
          java-version: '17'
      - name: Publish
        run: ./gradlew publishPlugin -Pversion=${{ github.event.inputs.version }}
        env:
          IJ_REPO_TOKEN: ${{ secrets.IJ_REPO_TOKEN }}